version: "3.8"

services:
  portainer_proxy:
    image: ghcr.io/jsh32/portainer-proxy:latest
    restart: always
    environment:
      - PORTAINER_HOSTNAME=portainer
    networks:
      - portainer_proxy
    ports:
      - 9000:80

  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    networks:
      - portainer_proxy
    ports:
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

networks:
  portainer_proxy:


volumes:
  portainer_data:
